# Generated by Django 6.0.3 on 2026-03-22 04:37

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department.', max_length=64, unique=True)),
                ('short_name', models.CharField(help_text='Short name that is used in the URL.', max_length=8, unique=True)),
                ('supervisor', models.ForeignKey(help_text='Points to a user, typically the supervisor, or any user that will manage the contacts associate with this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('extension', models.IntegerField()),
                ('location', models.CharField(max_length=64)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='django_phonedir.department')),
            ],
        ),
        migrations.CreateModel(
            name='FaxNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('location', models.CharField(max_length=64)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faxnumbers', to='django_phonedir.department')),
            ],
        ),
    ]
